linters:
  enable-all: true
  disable:
    - godox
    - gomnd

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - funlen
        - gocognit
        - gocritic
        - scopelint
