version: 2

jobs:
  test:
    docker:
      - image: circleci/golang:1.11.2
    working_directory: /go/src/github.com/MarioCarrion/nit
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go test -v ./...
  lint:
    docker:
      - image: mariocarrion/nit:v0.1.1
    working_directory: /go/src/github.com/MarioCarrion/nit
    environment:
      CGO_ENABLED: 0
    steps:
      - checkout
      - run: gometalinter --skip=vendor --skip=testdata --enable-all --config=.gometalinter.json ./...
  release:
    docker:
      - image: circleci/golang:1.11.2
    working_directory: /go/src/github.com/MarioCarrion/nit
    steps:
      - checkout
      - run: curl -sL https://git.io/goreleaser | bash

workflows:
  version: 2
  test_and_lint:
    jobs:
      - test
      - lint
  release:
    jobs:
      - release:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v[0-9]+(\.[0-9]+)*(-.*)*/
